### ISSUE TITLE
Output Question

### ISSUE THREAD

**Issue by thatryan** [aristath/kirki#1]
This looks awesome, thank you for sharing this hard work.

The output option requiring a stylesheet id, does this mean the CSS will be output to a file instead of inline in the head?

**Comment by aristath** [comment]
Hey there!
The `output` option in the background control outputs the CSS inline using the [wp_add_inline_style](http://codex.wordpress.org/Function_Reference/wp_add_inline_style) function as seen here: https://github.com/aristath/kirki/blob/0.3/includes/functions/background-css.php#L54

As seen on the [WordPress codex](http://codex.wordpress.org/Function_Reference/wp_add_inline_style), this function is used like this:

``` php
<?php wp_add_inline_style( $handle, $data ); ?>
```

The resulting CSS is then "appended" to the stylesheet that has the specific `handle` and is added inline.
It's the same as using an action to add our styles manually to `wp_head` but it's the WordPress recommended method of adding inline styles.
