### ISSUE TITLE
Please add collaborator so I can merge

### ISSUE THREAD

**Issue by ghost** [aristath/kirki#16]
Hi there,

Please add me as collaborator so I can merge some commits, as well as make some updates to the Kirki project.
- Ciaran

**Comment by aristath** [comment]
Hey there! You can simply fork the project and then submit a pull request to the repo. :)
You can see how to do that here: https://help.github.com/articles/creating-a-pull-request

**Comment by ghost** [comment]
Hi there. I have had 3 PRs sitting there for a couple of weeks and didn't see anything happen with them. 

Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Aristeides Stathopoulos notifications@github.com </div><div>Date:23/07/2014  5:53 AM  (GMT+09:30) </div><div>To: aristath/kirki kirki@noreply.github.com </div><div>Cc: Ciaran Whelan cmwwebfx@gmail.com </div><div>Subject: Re: [kirki] Please add collaborator so I can merge (#16) </div><div>
</div>Hey there! You can simply fork the project and then submit a pull request to the repo. :)
You can see how to do that here: https://help.github.com/articles/creating-a-pull-request

**Comment by aristath** [comment]
Oops... Sorry, I must have missed them! I'll check them out first thing in the morning (it's almost 2am where I live and I'm on my mobile right now).

**Comment by ghost** [comment]
No issue, that is why I thought if you have a new collaborator on board
then we can get this all done with ease. We are making the switch to use
Kirki on our work, so will be happy to add features.
