### ISSUE TITLE
3.0.26 is killing all of FontAwesome

### ISSUE THREAD

**Issue by tsquez** [aristath/kirki#1873]
Hi there,

Just wanted you to know that your new 3.0.26 update does something to Font Awesome.

I load Font Awesome myself, separate of Kirki, and after I updated, all of my font awesome icons disappeared. So I went back to 3.0.25 and they reappeared again.

Had some other people using my theme and they have sent me messages telling me the same thing.

So something is def wrong with the update.

**Comment by aristath** [comment]
Followed up on https://wordpress.org/support/topic/3-0-26-is-killing-all-of-fontawesome/#post-10226300 which was posted pretty much at the same time so I'm closing this one as a duplicate
