### ISSUE TITLE
wp_enqueue_styles

### ISSUE THREAD

**Issue by grappler** [aristath/kirki#2]
You could just directly use `wp_enqueue_style` instead of using `wp_register_style` first.

``` php
wp_enqueue_style( 'kirki-customizer-css', $kirki_url . 'assets/css/customizer.css', NULL, NULL, 'all' );
wp_enqueue_style( 'kirki-customizer-ui',  $kirki_url . 'assets/css/jquery-ui-1.10.0.custom.css', NULL, NULL, 'all' );
```

https://github.com/aristath/kirki/blob/master/kirki.php#L61

Why are you not adding a version when enqueue it? I know by not changing the version when you update the css then depending on the hosting caching it will not update.

**Comment by aristath** [comment]
Thanks for the suggestion. :+1: 

Fixed.
