### ISSUE TITLE
Issue List Cleanup

### ISSUE THREAD

**Issue by niklasp** [aristath/kirki#2026]
### Issue description:
There are many issues here that are outdated. I want to help you close them by referencing them in this issue. We can work more nicely on big things if issuelist is not polluted with old stuff imho.

I'd also like to help you **labeling them** that we have more view on programming issues. I'd need a different status on the project for that though. First categorization i'd love to make is introducing a "💬support" label for all settings-related questions that are more about specific kirki setting

**Comment by aristath** [comment]
@niklasp I agree that the issues list needs cleaning up.
But please don't comment on all issues unless there's something actually useful in the response. 
I usually go through them according to the number of comments and their recency. There are occasional cleanups, but adding comments to old issues just makes it harder to prioritize what has to be done first as they get to the front of the queue.

**Comment by niklasp** [comment]
ok i see
