### ISSUE TITLE
Turn off the custom styles

### ISSUE THREAD

**Issue by daviedR** [aristath/kirki#22]
Hi, I found this library is very interesting and awesome. Can't wait to try it on my upcoming theme. However, when I succeed to install it, I notice that you change the default WP customizer style with your own (dark colored). I prefer to use WP default style, can you show me how can I do it?

Thanks!

**Comment by aristath** [comment]
Hey there! I think our last commit addresses this issue.
If no custom colors are specified, then we use the default colors chosen by the user's admin theme.
