### ISSUE TITLE
jQuery UI elements not rendering because of ID selector

### ISSUE THREAD

**Issue by doitmax** [aristath/kirki#24]
You should consider to use jQuery <code>Attribute Equals Selector</code> for your ID selectors in the custom controls jQuery calls for UI elements (slider, image radios etc). A problem occurs when using ID's like <code>my_options[my_setting]</code> for a setting to save the theme_mod options in just one database entry as a serialized array. 

http://api.jquery.com/attribute-equals-selector/

With the current selector syntax, the jQuery UI elements are not rendered because the brackets in the ID selector are not escaped. You could escape those brackets in the with double backslashes or simple use the <code>Attribute Equals Selector</code> for the ID.

Instead of:

<code>$( '#input_<?php echo $this->id; ?>' ).buttonset();</code> 

you should consider to change it to:

<code>$( '[id="input_<?php echo $this->id; ?>"]' ).buttonset();</code> for example.

doitmax

**Comment by fovoc** [comment]
Thanks for the info on this. I changed the little snippet that handles the required field.

**Comment by doitmax** [comment]
Hi, thanks for getting back. 

Unfortunately this is not the only place to change it. You also have to change it on the controls where the jQuery UI scripts are called:

<code>/kirki/includes/controls/class-Kirki_Customize_Radio_Control.php</code>

<pre>
$( '[id="input_<?php echo $this->id; ?>"]' ).buttonset();
</pre>

<code>/kirki/includes/controls/class-Kirki_Customize_Sliderui_Control.php</code>

<pre>
$( '[id="slider_<?php echo $this->id; ?>"]' ).slider({
    value : <?php echo $this->value(); ?>,
    min   : <?php echo $this->choices['min']; ?>,
    max   : <?php echo $this->choices['max']; ?>,
    step  : <?php echo $this->choices['step']; ?>,
    slide : function( event, ui ) { $( '[id="input_<?php echo $this->id; ?>"]' ).val(ui.value).keyup(); }
});
$( '[id="input_<?php echo $this->id; ?>"]' ).val( $( '[id="slider_<?php echo $this->id; ?>"]' ).slider( "value" ) );
</pre>

And to make it more bulletproof, you should use the brackets for the attribute equals selector.

<pre>
$( '[id="input_<?php echo $this->id; ?>"]' )
</pre>

Cheers :)

**Comment by fovoc** [comment]
Thanks for the feedback on this! Feel free to create a pull-request for future suggestions. :+1: 

Cheers,
Dimitris
