### ISSUE TITLE
Multiselect is not turned off when false

### ISSUE THREAD

**Issue by sebastianthulin** [aristath/kirki#2458]
### Issue description:
Previously, we could use boolean values to turn on/off multisielect in https://kirki.org/docs/controls/select/. This dosen't seem to be the case anymore. The value 'multiple'    => false will keep multiselect enabled. This is quite confusing behaviour. A loose check with !empty() may be implemented. 

### Version used:
4.0.20

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
\Kirki::add_field(\Municipio\Customizer::KIRKI_CONFIG, [
    'type'        => 'select',
    'multiple'    => false,
    'settings'    => 'column_size_right',
    'label'       => esc_html__('Right', 'municipio'),
    'section'     => self::SECTION_ID,
    'default'     => 'normal',
    'priority'    => 20,
    'choices'     => [
        'normal' => esc_html__('Normal', 'municipio'),
        'large' => esc_html__('Large', 'municipio'),
    ],
    'output' => [
        'type' => 'controller'
    ],
 ]);
```

**Comment by mapsteps** [comment]
We're looking into this.

Generally speaking, passing multiple is not necessary if multiselect should be disabled. Not passing it or setting it to 1 should work.

**Comment by sebastianthulin** [comment]
This was my solution at the moment. The only issue here might be unnecessary confusion. A good thing to avoid. :)

**Comment by contactjavas** [comment]
Hi @sebastianthulin this issue has been fixed and the fix will be shipped in the next release.
For now, let me close this issue.

**Comment by sebastianthulin** [comment]
Thank you! Always a pleashure to working with you!
