### ISSUE TITLE
googlefonts() function forces http

### ISSUE THREAD

**Issue by JohEngstrom** [aristath/kirki#29]
The URL in the [googlefonts() function in kirki.php on line 81](https://github.com/presscodes/kirki/blob/master/kirki.php#L81) is hard coded to http so it produces warnings in the WordPress admin when define('FORCE_SSL_ADMIN', true); is set in wp-config.php.

I changed the URL from http://... to //... to fix this on my install.

**Comment by fovoc** [comment]
Hey there,

thanks for the feedback on this. Could you create  a pull-request for that or should I proceed with the bugfix?

Please advise,
Dimitris

**Comment by JohEngstrom** [comment]
I'm not too clued up on git yet so wouldn't know where to start sorry. Something I have to learn still!
