### ISSUE TITLE
Syntax Error When Embedding

### ISSUE THREAD

**Issue by digisavvy** [aristath/kirki#3]
Hey there!
Great project! I'm looking to embed this into my theme and I'm getting this error: 
Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /Users/Alex/Documents/Websites/somelikeitneat.dev/wp-content/themes/some-like-it-neat/library/inc/kirki/includes/functions/background-css.php on line 17

I was able to resolve this by using the code from the WP Repo plugin, the Github version is different/behind apparently.

Cheers!

**Comment by aristath** [comment]
Yeah, I've seen that error too though it doesn't make any sense! The syntax used was perfectly fine... I suspect this has to do with the server used. 
In any case, this has been fixed in https://github.com/aristath/kirki/commit/07aa00130c521c42ad8ae718f5c754a73bbb3444
